### PR TITLE
Feature/mms 1783/sticky control bar

### PR DESCRIPTION
**Pull request by AlexanderLyz**

### CODE REVIEW

**Review by ericbdev — APPROVED** [review]
Should this be a default behavior of Editor? How would you feel about the suite (mmx) making it sticky?

**Comment by ericbdev** [comment]
@AlexanderLyz Please respond to the question on this PR :)

**Comment by AlexanderLyz** [comment]
> Should this be a default behavior of Editor? How would you feel about the suite (mmx) making it sticky?

I believe that it's ok to make it sticky by default, cause this is most useful behavior. We can make it not-sticky in mmx if we need, but if i get it clear there are no cases where we need that. So why should we change mmx in several places to make it sticky if we can do it once in editor? I'm open to discuss it & if you think that we have to change this behavior, of course we can do it

**Comment by ericbdev** [comment]
What concerns me is, Editor Editor is pretty specific about being implementation agnostic. Looking at the ticket MMS-1783, it only refers to MMX capabilities.  If you look at the code, the only place we place Toolbar statically is in MMS Editor, and in fact, it is styled via ToolbarWrapper.

So the only usecase we wanted to effect here is static toolbar. I think id also vote that if we're making a default behavior, it should be via a linked style sheet, not inline style. Inline style is the most specific you can get, making it the hardest to adjust via cascading styles.

**Comment by AlexanderLyz** [comment]
Ok, i agree, inline style is not the best way. So i'll just remove this changes & make it sticky in mmx if we really don't want it to be default behavior

**Pull request merged**
